src/integTest/groovy/nebula/plugin/release/ReleasePluginNewProjectIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

Also, do not fail when `git init` has been run, but there is no initial commit yet.

Warn rather than fail when git repository does not exist

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy

The  implementation of ReleaseLastTagStrategy created a new TagStrategy object instead of using the one defined in `release` extension. Which in a case of custom logic of parsing and producing version tags  could cause  `-Prelease.useLastTag=true` option not to work properly.

Updated ReleaseLastTagStrategy to honour a tag strategy set in `release` extension

---

CHANGELOG.md
src/integTest/groovy/nebula/plugin/release/ReleasePluginNoCommitIntegrationSpec.groovy
src/integTest/groovy/nebula/plugin/release/ReleasePluginNoRepoIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

The try catch seems a little dirty but probably the easiest way to determine if its an empty repo that I can see. If you guys have a better idea from grgit or jgit will swap.

Allow plugin to work with no git repo or one with no commits. Fixes #59.

---

.travis.yml
build.gradle
dependencies.lock

This upgrade transitively pulls in a new version of jgit, which fixes [Bug 498759: jgit shows submodule as modified path](https://bugs.eclipse.org/bugs/show_bug.cgi?id=498759).

Upgrade gradle-git

---

src/main/groovy/nebula/plugin/release/ErrorMessageFormatter.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/test/groovy/nebula/plugin/release/ErrorMessageFormatterSpec.groovy

Produces a list of files that are added, modified, or removed (staged or unstaged) or newly in conflict. The plugin now also uses GrGit's `isClean` logic, which considers staged, unstaged, and conflicts.
This should help troubleshoot in situations where JGit and git differ in their opinion of whether or not the workspace is clean.

List Files Considered Changed When !isClean()

---

src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/test/groovy/nebula/plugin/release/ReleasePluginOptionalDepsSpec.groovy

Avoid BuildInfoBaseTask class check. Safety migrate to ArtifactoryTask because jfrog delete base class since build-info-extractor 4.6.0 [GAP-281](https://www.jfrog.com/jira/browse/GAP-281)

GAP-281 – Avoid using removed BuildInfoBaseTask i

---

src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy
src/test/groovy/nebula/plugin/release/git/base/BaseReleasePluginSpec.groovy

`nebula-release` plugin was modified to include code from `gradle-git`.
During the migration of this code, the tests were moved as of that day and now that we are moving to gradle 5, tests in `BaseReleasePluginSpec` won't execute because `TaskInternal.execute()` was removed in https://github.com/gradle/gradle/commit/6521f6cde0de047822d590a164fa933a0530ff1f#diff-5a073fcafa933576d519372602f7d109
Doing the following is not a good pattern `project.tasks.prepare.execute()`

BaseReleasePluginSpec refactor

---

build.gradle

jgit is currently throwing a 
```No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef()``` in some scenarios, but upgrading to the latest fixes this problem
cc @tgianos

Include dependency constraint on jgit

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/NetflixOssStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

`NetflixOssStrategies.project = project` was detected as a potential memory leak.
This quick refactor is just to stop doing this and instead pass the project as an argument and use it to determine the `release.travisBranch` property.
While this introduces a breaking change such as 
`defaultVersionStrategy = nebula.plugin.release.NetflixOssStrategies.SNAPSHOT(project)` in favor of `nebula.plugin.release.NetflixOssStrategies.SNAPSHOT`, I believe it would be ok for now since we are the only consumers of this strategy and we don't use it heavily.
Unfortunately, other strategies do not depend on project properties so it makes easier to do everything in a static context -> https://github.com/nebula-plugins/nebula-release-plugin/blob/master/src/main/groovy/nebula/plugin/release/git/opinion/Strate …

Refactor netflixossstrategies

---

src/main/groovy/nebula/plugin/release/git/base/ReleaseVersion.groovy

DelayedVersion is already Serializable, so this makes sense.
Fixes #139

Make ReleaseVersion Serializable

---

README.md
src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/integTest/groovy/nebula/plugin/release/ReleasePluginIvyStatusIntegrationSpec.groovy
src/integTest/groovy/nebula/plugin/release/SnapshotResolutionIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/NetflixOssStrategies.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/opinion/OpinionReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/opinion/Strategies.groovy
src/main/groovy/nebula/plugin/release/git/opinion/TimestampUtil.groovy
src/test/groovy/nebula/plugin/release/git/opinion/OpinionReleasePluginSpec.groovy
src/test/groovy/nebula/plugin/release/git/opinion/StrategiesSpec.groovy

This introduces `immutableSnapshot` task/strategy to generate snapshot versions that are meant to be immutable and should be unique via UTC timestamp. Ex. `1.2.0-snapshot.20190705210556893+abcdef`  
Pattern is  `<major>.<minor>.<patch>-snapshot.<timestamp>+<hash>` and timestamp format is `YYYYMMddHHmmssSSS`
This change doesn't replace `devSnapshot` and default strategy to prevent breaking changes for consumers.
We should be able to override the default strategy from `devSnapshot` to `immutableSnapshot` via `ReleasePluginExtension`:
```
release {
defaultVersionStrategy = nebula.plugin.release.NetflixOssStrategies.IMMUTABLE_SNAPSHOT(project)
}
```

Introduce ImmutableSnapshot strategy to create snapshots using timestamps

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/integTest/groovy/nebula/plugin/release/ReleasePluginNoCommitIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/FeatureFlags.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

This is for people trying to leverage `immutableSnapshot` without the need of re-writing infrastructure that uses `devSnapshot` task.
Unfortunately, modifying task configuration in consumers isn't enough. Ex.
```
TaskContainer tasksContainer = project.rootProject.tasks
Task devSnapshot = tasksContainer.findByName('devSnapshot')
Task immutableSnapshot = tasksContainer.findByName('immutableSnapshot')
if(!immutableSnapshot || !devSnapshot) {
logger.debug("immutableSnapshot and/or devSnapshot tasks are not present. Skipping immutable snapshot configuration")
return
}
devSnapshot.dependsOn(immutableSnapshot)
devSnapshot.enabled = false
```
While this instructs Gradle to execute `immutableSnapshot` task and disable `devSnapshot` this doesn't work as expected.
This is because release plugin uses …

Introduce feature flag to replace devSnapshot with immutableSnapshot under the hood

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/git/opinion/Strategies.groovy
src/test/groovy/nebula/plugin/release/git/opinion/StrategiesSpec.groovy

This is a proposal for fixing the case where generating candidate results in `1.0.0-rc.1` and next `devSnapshot` will be come `1.0.0-rc.1.dev.3...`
Ideally it should be ``1.0.0.dev.3...` as you continue snapshots on the same major/minor/patch
Per @rspieldenner comments:
```
I would expect a candidate producing 2.1.0-rc.2 and then a devSnapshot would return to 2.1.0-dev.#+hash
``` 
This is a breaking change

devSnapshot - remove attaching of STAGE_FLOAT

---

build.gradle
src/groovyCompile/groovycConfig.groovy
src/main/groovy/nebula/plugin/release/ErrorMessageFormatter.groovy
src/main/groovy/nebula/plugin/release/FeatureFlags.groovy
src/main/groovy/nebula/plugin/release/NetflixOssStrategies.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleaseExtension.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/VersionSanitizerUtil.groovy
src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/base/ReleasePluginExtension.groovy
src/main/groovy/nebula/plugin/release/git/base/ReleaseVersion.groovy
src/main/groovy/nebula/plugin/release/git/base/TagStrategy.groovy
src/main/groovy/nebula/plugin/release/git/experimental/ExperimentalReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/opinion/OpinionReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/opinion/Strategies.groovy
src/main/groovy/nebula/plugin/release/git/semver/NearestVersionLocator.groovy
src/main/groovy/nebula/plugin/release/git/semver/RebuildVersionStrategy.groovy
src/main/groovy/nebula/plugin/release/git/semver/SemVerStrategy.groovy
src/main/groovy/nebula/plugin/release/git/semver/SemVerStrategyState.groovy
src/main/groovy/nebula/plugin/release/git/semver/StrategyUtil.groovy
src/main/groovy/nebula/plugin/release/util/ObjectUtil.java
src/test/groovy/nebula/plugin/release/git/base/TagStrategySpec.groovy

We can revisit this plugin later as we leverage `copyWith` from `ImmutableAnnotation` which doesn't play well with static compilation out of the box -> http://docs.groovy-lang.org/2.4.7/html/gapi/groovy/transform/Immutable.html#copyWith

Introduce static compilation

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/ReleaseExtension.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

The idea of this is to disable `prepare` by default and opt-in by setting `checkRemoteBranchOnRelease` at extension level.
The rationale for this is to allow continuous delivery where a user might change the branch when an existing release is happening. `prepare` fails builds if the branch is behind (https://github.com/nebula-plugins/nebula-release-plugin/blob/4c4f364547ac093f7a1acb22644d4f4654cf0bb4/src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy#L89) 
NOTE: this doesn't disable the `release` task as that might have different outputs

Introduce checkRemoteBranchOnRelease in ReleaseExtension to disable prepare task

---

README.md

I have tested this with version 13.1.1. Using `-Prelease.sanitizeVersion=true` was the only thing that worked.

Fix documentation how to sanitize versions

---

src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy
src/test/groovy/nebula/plugin/release/ReleasePluginConfigurationAvoidanceSpec.groovy

I had a problem with running nebula-release alongside cognifide aem plugin. I wrote about this on the [discussion board](https://discuss.gradle.org/t/mediating-between-nebula-release-and-cognifide-aem-which-one-is-right/33954) but got no replies so far.
I switched the code that ensures the `prepare` task runs before all others to use the task configuration avoidance API [as described](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview).
There are lots of other places where we should be conforming to best practices and use the task configuration avoidance rather than the explicit task API and I only fixed the code that forced the configurations of all tasks to be non-lazily evaluated. This should fix the bulk of the …

feat(performance): don’t force tasks to be created

---

src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/experimental/ExperimentalReleasePlugin.groovy

As promised in #172, I tried to replace more usages of the old explicit task API with the [task avoidance best practices](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview).
The tests all run through but I’m not sure I didn’t break anything. Also I didn’t add a new test as I wasn’t really sure what to test for…

Avoid configuring tasks

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

This is to prevent issues like:
```
> Failed to apply plugin ['']
> Could not resolve all dependencies for configuration ':mytask'.
> Identifiers MUST NOT be empty
Caused by: Identifiers MUST NOT be empty (Unexpected character 'DOT(.)' at position '24', expecting '[DIGIT, LETTER, HYPHEN]')
at com.github.zafarkhaja.semver.VersionParser.checkForEmptyIdentifier(VersionParser.java:498)
at com.github.zafarkhaja.semver.VersionParser.buildIdentifier(VersionParser.java:384)
at com.github.zafarkhaja.semver.VersionParser.parseBuild(VersionParser.java:361)
at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:264)
at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
at com.github.zafarkhaja.semver.Version$Builder.build(Version.java:158) …
```

ReleasePlugin.checkForBadBranchNames should fail if branch ends with dash

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/test/groovy/nebula/plugin/release/OverrideStrategiesSpec.groovy

In order to keep consistency with version calculation, the plugin should fail with non-semver versions
`ignoreSuppliedVersionVerification` flag is available when desired to bypass this

Using a non-semver version for release.version should fail

---

src/main/groovy/nebula/plugin/release/git/semver/SemVerStrategy.groovy

Git status can be really slow on repositories with deep history.
I wonder if we could use an alternative for checking dirty?
https://stackoverflow.com/a/2658301/364206
For instance on `gradle/gradle`:
```
git status --porcelain  0.12s user 0.40s system 154% cpu 0.342 total
git diff --shortstat  0.08s user 0.21s system 304% cpu 0.093 total
```
Looking at `StatusCommand` it appears it's just doing a diff anyway. This looks even better:
```
git diff-index --quiet HEAD  0.03s user 0.19s system 618% cpu 0.035 total
```
But it looks like those alternatives only catch changed files, not new files not in the index.

Avoid git status call for strategy selection unless required

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/git/opinion/Strategies.groovy

This fixes https://github.com/nebula-plugins/nebula-release-plugin/issues/199
We found that 
```
git.tag.add(name: 'v3.1.2')
git.tag.add(name: 'v3.2.0-rc.1')
git.tag.add(name: 'v3.2.0-rc.2')
when:
def version =  inferredVersionForTask('devSnapshot', '-Prelease.scope=patch')
then:
version == dev('3.1.3-dev.0+') 
```
However, doing this with immutable snapshots:
```
replaceDevWithImmutableSnapshot()
git.tag.add(name: 'v3.1.2')
git.tag.add(name: 'v3.2.0-rc.1')
git.tag.add(name: 'v3.2.0-rc.2')
when:
def version =  inferredVersionForTask('devSnapshot', '-Prelease.scope=patch')
then:
version.toString().startsWith("3.1.3-snapshot." + getUtcDateForComparison()) 
```
results in exceptions such as 
```
11:49:17 Caused by: org.gradle.api.GradleException: Based on previous tags in this branch the …
```

nebula.release should not enforce precedence for immutable snapshots

---

src/integTest/groovy/nebula/plugin/release/DefaultVersionStrategyOverrideViaPropertyIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy

Because Extension values are available after project evaluation, it might be too late for version inference. This adds support to pass a class name to instantiate a versioning strategy and used that. This could be used to obtain versions not only from tags / semver but external services

Add support for passing a versioning strategy class name as project property

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/git/command/GitCommandParameters.groovy
src/main/groovy/nebula/plugin/release/git/command/GitReadCommand.groovy
src/main/groovy/nebula/plugin/release/git/command/GitReadOnlyCommandUtil.groovy
src/main/groovy/nebula/plugin/release/git/command/GitWriteCommandsUtil.groovy
src/main/groovy/nebula/plugin/release/git/semver/NearestVersionLocator.groovy

The initial refactor to use native git introduced a big performance hit:
```
2023-11-08T16:37:04.041-0800 [DEBUG] [nebula.plugin.release.git.semver.NearestVersionLocator] Locate beginning on branch: testing
2023-11-08T16:37:56.318-0800 [DEBUG] [nebula.plugin.release.git.semver.NearestVersionLocator] Nearest release: {version=9.5.0, distance=73}, nearest any: {version=10.0.0-rc.1, distance=1}.
```
Historically, we have iterated over all tags and sort them by distance in order to determine which one is closer. Unfortunately, when doing git native calls, it is way less performant that in memory git representation with jgit. This change to native git contributed to ~50s of configuration time for a project that has ~1.2k tags 
After looking into the actual purpose and even description of the …

Refactor NearestVersionLocator to reduce the number of native git calls

---

src/main/groovy/nebula/plugin/release/OverrideStrategies.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/command/GitReadOnlyCommandUtil.groovy
src/main/groovy/nebula/plugin/release/util/ReleaseTasksUtil.groovy
src/test/groovy/nebula/plugin/release/util/ReleaseTasksUtilSpec.groovy

We probably should require git user information only when creating and pushing tags so that only applies to `candidate` and `final` tasks when `release.useLastTag` is not used.

Only verify git user information when creating and pushing tags. 

---

src/integTest/groovy/nebula/plugin/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/nebula/plugin/release/ReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/base/BaseReleasePlugin.groovy
src/main/groovy/nebula/plugin/release/git/base/ReleasePluginExtension.groovy

Hi folks!
This adds support for relative paths in `git.root` in a way that seems recommended from [Gradle's docs](https://docs.gradle.org/current/userguide/working_with_files.html#sec:single_file_paths).
From a quick glance at the implementation it looks like this could be converted to use `providerFactory.gradleProperty('git.root')` with a convention and mapping to a file instance. I didn't take this step because it's a larger change.
I have a project that attempts to set `git.root=..` in a nested directory. It looks like this:
```
rootDir
my-gradle-project
build.gradle
settings.gradle
gradle.properties
other-project
```
I recently started getting a failure during Gradle's configuration phase that `..` must be an absolute path, demonstrated by the included test.

Support relative paths in `git.root`
